import { useLocation, Link } from 'react-router-dom';
import { FaFileWord, FaFilePdf, FaArrowLeft, FaCheckCircle, FaSpinner } from 'react-icons/fa';
import axios from 'axios';
import { useState } from 'react';

const ResultPage = () => {
    const location = useLocation();
    const { data } = location.state || {};
    const [downloading, setDownloading] = useState(false);

    if (!data) return (
        <div className="min-h-[60vh] flex flex-col items-center justify-center p-6 text-center">
            <h2 className="text-2xl font-bold text-slate-300 mb-4">No content available</h2>
            <Link to="/upload" className="px-6 py-2 bg-blue-600 text-white rounded-full hover:bg-blue-700 transition">Go to Upload</Link>
        </div>
    );

    const handleDownload = async (format) => {
        setDownloading(true);
        try {
            const response = await axios.post('/api/download', {
                markdown: data.markdownContent,
                format
            }, { responseType: 'blob' });

            const url = window.URL.createObjectURL(new Blob([response.data]));
            const link = document.createElement('a');
            link.href = url;
            link.setAttribute('download', `converted_document.${format}`);
            document.body.appendChild(link);
            link.click();
            link.parentNode.removeChild(link);
        } catch (error) {
            console.error("Download failed", error);
            alert("Download failed. Please try again.");
        }
        setDownloading(false);
    };

    return (
        <div className="max-w-6xl mx-auto px-6 py-12">
            <Link to="/upload" className="inline-flex items-center text-slate-500 dark:text-slate-400 hover:text-blue-600 dark:hover:text-blue-400 mb-8 transition font-medium">
                <FaArrowLeft className="mr-2" /> Convert Another File
            </Link>

            <div className="bg-white dark:bg-slate-800 rounded-3xl shadow-2xl overflow-hidden border border-slate-100 dark:border-slate-700">
                <div className="bg-slate-900 dark:bg-black p-8 text-white md:flex justify-between items-center">
                    <div className="mb-6 md:mb-0">
                        <h1 className="text-3xl font-bold flex items-center gap-3 mb-2">
                            <FaCheckCircle className="text-green-400" /> Success!
                        </h1>
                        <p className="text-slate-400">
                            AI Detected Type: <span className="text-blue-400 font-semibold bg-blue-400/10 px-2 py-0.5 rounded ml-1">{data.detectedType}</span>
                        </p>
                    </div>

                    <div className="flex flex-col sm:flex-row gap-4">
                        <button
                            onClick={() => handleDownload('docx')}
                            disabled={downloading}
                            className="flex items-center justify-center gap-2 bg-blue-600 hover:bg-blue-700 text-white px-6 py-3 rounded-xl font-bold transition shadow-lg shadow-blue-900/20 disabled:opacity-50"
                        >
                            {downloading ? <FaSpinner className="animate-spin" /> : <FaFileWord />}
                            Download Word
                        </button>
                        <button
                            onClick={() => handleDownload('pdf')}
                            disabled={downloading}
                            className="flex items-center justify-center gap-2 bg-slate-700 hover:bg-slate-600 text-white px-6 py-3 rounded-xl font-bold transition disabled:opacity-50 border border-slate-600"
                        >
                            {downloading ? <FaSpinner className="animate-spin" /> : <FaFilePdf />}
                            Download PDF
                        </button>
                    </div>
                </div>

                <div className="p-8 bg-slate-50 dark:bg-slate-900/50">
                    <div className="flex justify-between items-center mb-4">
                        <h3 className="text-xs font-bold text-slate-400 uppercase tracking-widest">Document Preview</h3>
                        <span className="text-xs text-slate-400">Generated by Gemini AI</span>
                    </div>

                    <div className="bg-white dark:bg-slate-950 p-8 rounded-xl border border-slate-200 dark:border-slate-800 shadow-sm font-serif text-slate-800 dark:text-slate-200 whitespace-pre-wrap overflow-auto max-h-[600px] leading-relaxed">
                        {data.markdownContent}
                    </div>
                </div>
            </div>
        </div>
    );
};
export default ResultPage;
